# Stage 1: Build the Angular application
FROM node:18.18-alpine3.18 AS build

# set the working directory to /app
WORKDIR /app

# copy packages
COPY package*.json ./

# install dependencies, matching package-lock.json
RUN npm ci

RUN npm install -g @angular/cli

# copy the current directory contents into the container at /app
COPY . .

RUN npm run build --configuration=production

# Use the latest version of the official Nginx image as the base image
FROM nginx:latest
# copy the custom nginx configuration file to the container in the default
# location
COPY ./nginx.conf /etc/nginx/conf.d/default.conf
# copy the built application from the build stage to the nginx html
# directory
COPY --from=build /app/dist/asset-managment/browser /usr/share/nginx/html
#COPY --from=builder /app/dist/project1 /usr/share/nginx/html/project1
#COPY --from=builder /app/dist/project2 /usr/share/nginx/html/project2
EXPOSE 4200

